# GNU/Linux makefile for ReTrace.

MAIN_CLASS       = proguard/retrace/ReTrace
CLASSPATH        = ../base/$(OUT):../core/$(OUT)
TARGET           = retrace
INCLUDE_MANIFEST = true

include ../buildscripts/functions.mk
