package proguard.obfuscate;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Test class for PrefixingNameFactory.nextName() method.
 * Tests that the method properly prepends a prefix to names generated by the delegate NameFactory.
 */
public class PrefixingNameFactoryClaude_nextNameTest {

    /**
     * Test that nextName prepends the prefix to the delegate's name.
     */
    @Test
    public void testNextNamePrependsPrefix() {
        NameFactory delegate = new SimpleNameFactory();
        PrefixingNameFactory factory = new PrefixingNameFactory(delegate, "prefix_");

        String name = factory.nextName();

        assertTrue(name.startsWith("prefix_"),
            "Generated name should start with the prefix");
    }

    /**
     * Test that nextName generates different names on subsequent calls.
     */
    @Test
    public void testNextNameGeneratesDifferentNames() {
        NameFactory delegate = new SimpleNameFactory();
        PrefixingNameFactory factory = new PrefixingNameFactory(delegate, "test_");

        String name1 = factory.nextName();
        String name2 = factory.nextName();
        String name3 = factory.nextName();

        assertNotEquals(name1, name2,
            "First and second names should be different");
        assertNotEquals(name2, name3,
            "Second and third names should be different");
        assertNotEquals(name1, name3,
            "First and third names should be different");

        assertTrue(name1.startsWith("test_"));
        assertTrue(name2.startsWith("test_"));
        assertTrue(name3.startsWith("test_"));
    }

    /**
     * Test that nextName with empty prefix just returns delegate's name.
     */
    @Test
    public void testNextNameWithEmptyPrefix() {
        NameFactory delegate = new SimpleNameFactory();
        PrefixingNameFactory factory = new PrefixingNameFactory(delegate, "");

        String name = factory.nextName();

        assertNotNull(name, "Name should not be null");
        assertFalse(name.isEmpty(), "Name should not be empty");
    }

    /**
     * Test that nextName with single character prefix works correctly.
     */
    @Test
    public void testNextNameWithSingleCharPrefix() {
        NameFactory delegate = new SimpleNameFactory();
        PrefixingNameFactory factory = new PrefixingNameFactory(delegate, "x");

        String name = factory.nextName();

        assertTrue(name.startsWith("x"),
            "Name should start with 'x'");
        assertTrue(name.length() > 1,
            "Name should have more than just the prefix");
    }

    /**
     * Test that nextName with long prefix works correctly.
     */
    @Test
    public void testNextNameWithLongPrefix() {
        NameFactory delegate = new SimpleNameFactory();
        PrefixingNameFactory factory = new PrefixingNameFactory(delegate, "veryLongPrefixForTesting_");

        String name = factory.nextName();

        assertTrue(name.startsWith("veryLongPrefixForTesting_"),
            "Name should start with the long prefix");
    }

    /**
     * Test that nextName generates sequential names with prefix.
     */
    @Test
    public void testNextNameSequentialGeneration() {
        NameFactory delegate = new SimpleNameFactory();
        PrefixingNameFactory factory = new PrefixingNameFactory(delegate, "pre_");

        String name1 = factory.nextName();
        String name2 = factory.nextName();
        String name3 = factory.nextName();

        assertEquals("pre_a", name1,
            "First name should be prefix + 'a'");
        assertEquals("pre_b", name2,
            "Second name should be prefix + 'b'");
        assertEquals("pre_c", name3,
            "Third name should be prefix + 'c'");
    }

    /**
     * Test that nextName works with multiple PrefixingNameFactory instances.
     */
    @Test
    public void testNextNameMultipleInstances() {
        NameFactory delegate1 = new SimpleNameFactory();
        NameFactory delegate2 = new SimpleNameFactory();
        PrefixingNameFactory factory1 = new PrefixingNameFactory(delegate1, "alpha_");
        PrefixingNameFactory factory2 = new PrefixingNameFactory(delegate2, "beta_");

        String name1 = factory1.nextName();
        String name2 = factory2.nextName();

        assertTrue(name1.startsWith("alpha_"),
            "Factory1 should use alpha_ prefix");
        assertTrue(name2.startsWith("beta_"),
            "Factory2 should use beta_ prefix");
        assertEquals("alpha_a", name1);
        assertEquals("beta_a", name2);
    }

    /**
     * Test that nextName with numeric prefix works.
     */
    @Test
    public void testNextNameWithNumericPrefix() {
        NameFactory delegate = new SimpleNameFactory();
        PrefixingNameFactory factory = new PrefixingNameFactory(delegate, "123_");

        String name = factory.nextName();

        assertTrue(name.startsWith("123_"),
            "Name should start with numeric prefix");
    }

    /**
     * Test that nextName with special character prefix works.
     */
    @Test
    public void testNextNameWithSpecialCharPrefix() {
        NameFactory delegate = new SimpleNameFactory();
        PrefixingNameFactory factory = new PrefixingNameFactory(delegate, "$_");

        String name = factory.nextName();

        assertTrue(name.startsWith("$_"),
            "Name should start with special character prefix");
    }

    /**
     * Test that nextName maintains state across multiple calls.
     */
    @Test
    public void testNextNameMaintainsState() {
        NameFactory delegate = new SimpleNameFactory();
        PrefixingNameFactory factory = new PrefixingNameFactory(delegate, "state_");

        String name1 = factory.nextName();
        String name2 = factory.nextName();

        assertEquals("state_a", name1);
        assertEquals("state_b", name2);

        // Call again to verify state is maintained
        String name3 = factory.nextName();
        assertEquals("state_c", name3,
            "State should be maintained across calls");
    }

    /**
     * Test that nextName after reset starts from beginning with prefix.
     */
    @Test
    public void testNextNameAfterReset() {
        NameFactory delegate = new SimpleNameFactory();
        PrefixingNameFactory factory = new PrefixingNameFactory(delegate, "reset_");

        String name1 = factory.nextName();
        String name2 = factory.nextName();

        assertEquals("reset_a", name1);
        assertEquals("reset_b", name2);

        factory.reset();

        String name3 = factory.nextName();
        assertEquals("reset_a", name3,
            "After reset, nextName should start from beginning");
    }

    /**
     * Test that nextName generates many unique names with prefix.
     */
    @Test
    public void testNextNameGeneratesManyUniqueNames() {
        NameFactory delegate = new SimpleNameFactory();
        PrefixingNameFactory factory = new PrefixingNameFactory(delegate, "many_");

        java.util.Set<String> names = new java.util.HashSet<>();
        for (int i = 0; i < 100; i++) {
            names.add(factory.nextName());
        }

        assertEquals(100, names.size(),
            "Should generate 100 unique names");

        for (String name : names) {
            assertTrue(name.startsWith("many_"),
                "All names should have the prefix");
        }
    }

    /**
     * Test that nextName with underscore prefix works.
     */
    @Test
    public void testNextNameWithUnderscorePrefix() {
        NameFactory delegate = new SimpleNameFactory();
        PrefixingNameFactory factory = new PrefixingNameFactory(delegate, "_");

        String name = factory.nextName();

        assertTrue(name.startsWith("_"),
            "Name should start with underscore");
        assertEquals("_a", name);
    }

    /**
     * Test that nextName works with different delegate factory.
     */
    @Test
    public void testNextNameWithDifferentDelegate() {
        NameFactory delegate = new SimpleNameFactory(false); // lower-case only
        PrefixingNameFactory factory = new PrefixingNameFactory(delegate, "lower_");

        String name1 = factory.nextName();
        String name2 = factory.nextName();

        assertEquals("lower_a", name1);
        assertEquals("lower_b", name2);
    }

    /**
     * Test that nextName preserves delegate's naming pattern.
     */
    @Test
    public void testNextNamePreservesDelegatePattern() {
        NameFactory delegate = new SimpleNameFactory(true); // mixed-case
        PrefixingNameFactory factory = new PrefixingNameFactory(delegate, "mix_");

        // Generate enough names to see mixed-case pattern
        for (int i = 0; i < 26; i++) {
            factory.nextName();
        }

        String name = factory.nextName();

        assertTrue(name.startsWith("mix_"),
            "Name should have prefix");
        // The 27th name from SimpleNameFactory with mixed-case should be uppercase
        assertTrue(name.contains("A") || name.contains("B") || name.contains("C"),
            "Should eventually generate mixed-case names from delegate");
    }

    /**
     * Test that nextName doesn't modify the prefix.
     */
    @Test
    public void testNextNameDoesNotModifyPrefix() {
        NameFactory delegate = new SimpleNameFactory();
        PrefixingNameFactory factory = new PrefixingNameFactory(delegate, "constant_");

        String name1 = factory.nextName();
        String name2 = factory.nextName();
        String name3 = factory.nextName();

        assertTrue(name1.startsWith("constant_"));
        assertTrue(name2.startsWith("constant_"));
        assertTrue(name3.startsWith("constant_"));
    }

    /**
     * Test that nextName is never null.
     */
    @Test
    public void testNextNameNeverNull() {
        NameFactory delegate = new SimpleNameFactory();
        PrefixingNameFactory factory = new PrefixingNameFactory(delegate, "prefix_");

        for (int i = 0; i < 50; i++) {
            String name = factory.nextName();
            assertNotNull(name, "nextName should never return null");
        }
    }

    /**
     * Test that nextName is never empty when prefix is non-empty.
     */
    @Test
    public void testNextNameNeverEmpty() {
        NameFactory delegate = new SimpleNameFactory();
        PrefixingNameFactory factory = new PrefixingNameFactory(delegate, "prefix_");

        for (int i = 0; i < 50; i++) {
            String name = factory.nextName();
            assertFalse(name.isEmpty(), "nextName should never return empty string");
        }
    }

    /**
     * Test that nextName works correctly after many generations.
     */
    @Test
    public void testNextNameAfterManyGenerations() {
        NameFactory delegate = new SimpleNameFactory();
        PrefixingNameFactory factory = new PrefixingNameFactory(delegate, "long_");

        // Generate many names
        String lastNam = null;
        for (int i = 0; i < 1000; i++) {
            lastNam = factory.nextName();
        }

        assertNotNull(lastNam, "Should still generate names after many calls");
        assertTrue(lastNam.startsWith("long_"),
            "Should still have prefix after many calls");
    }

    /**
     * Test that nextName with camelCase prefix works.
     */
    @Test
    public void testNextNameWithCamelCasePrefix() {
        NameFactory delegate = new SimpleNameFactory();
        PrefixingNameFactory factory = new PrefixingNameFactory(delegate, "myPrefix");

        String name = factory.nextName();

        assertTrue(name.startsWith("myPrefix"),
            "Name should start with camelCase prefix");
        assertEquals("myPrefixa", name);
    }

    /**
     * Test that nextName with PascalCase prefix works.
     */
    @Test
    public void testNextNameWithPascalCasePrefix() {
        NameFactory delegate = new SimpleNameFactory();
        PrefixingNameFactory factory = new PrefixingNameFactory(delegate, "MyPrefix");

        String name = factory.nextName();

        assertTrue(name.startsWith("MyPrefix"),
            "Name should start with PascalCase prefix");
        assertEquals("MyPrefixa", name);
    }

    /**
     * Test that nextName works with shared delegate between instances.
     */
    @Test
    public void testNextNameWithSharedDelegate() {
        NameFactory delegate = new SimpleNameFactory();
        PrefixingNameFactory factory1 = new PrefixingNameFactory(delegate, "first_");
        PrefixingNameFactory factory2 = new PrefixingNameFactory(delegate, "second_");

        String name1 = factory1.nextName();
        String name2 = factory2.nextName();

        assertEquals("first_a", name1);
        // Since delegate is shared, it advances
        assertEquals("second_b", name2);
    }

    /**
     * Test that nextName with space in prefix works (though not typical).
     */
    @Test
    public void testNextNameWithSpaceInPrefix() {
        NameFactory delegate = new SimpleNameFactory();
        PrefixingNameFactory factory = new PrefixingNameFactory(delegate, "prefix ");

        String name = factory.nextName();

        assertTrue(name.startsWith("prefix "),
            "Name should start with prefix including space");
    }
}
